add option to clean host on migrate
coreymbe/pe_migrate pull request #4
Opened 2021-05-05 10:09 UTC by MartyEwings

Prior to this commit if the new host had a different CA, there was no option to clean the SSL certs on the agent

2021-05-05 10:09 UTC, MartyEwings commented
@pgrant87 @coreymbe --^

2021-05-10 23:09 UTC, coreymbe requested changes
Line 8 in agent_migrate.sh should be:

`if [ $CLEAN_HOST = true ]`

Aside from that, this one lgtm!

2021-05-12 18:16 UTC, coreymbe commented
> Line 8 in agent_migrate.sh should be:
> 
> 
> 
> if [ $CLEAN_HOST = true ]
> 
> 
> 
> Aside from that, this one lgtm!

@MartyEwings ^

2021-05-17 18:07 UTC, coreymbe approved these changes
LGTM!

2021-05-17 18:08 UTC, merged